# Generated by Django 3.2.11 on 2022-02-06 20:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [("authnapp", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="shopuser",
            name="activation_key_expires",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 2, 8, 20, 32, 0, 343418, tzinfo=utc), verbose_name="актуальность ключа"
            ),
        )
    ]
