# Generated by Django 3.2.11 on 2022-01-31 21:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [("authnapp", "0002_user_model_extend")]

    operations = [
        migrations.AlterField(
            model_name="shopuser",
            name="activation_key_expires",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 2, 2, 21, 30, 30, 565212, tzinfo=utc), verbose_name="актуальность ключа"
            ),
        )
    ]
